# Modified from https://github.com/Interbotix/widowx_arm/blob/master/widowx_arm_controller/config/arm.yaml

controllers: [shoulder_1, shoulder_2, elbow, wrist_1, wrist_2, wrist_3, gripper_joint]

joints: {
    joint_1: {id: 1, ticks: 4096, range: 360.0, max_speed: 100.0},
    joint_2: {id: 2, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 100.0},
    joint_3: {id: 3, ticks: 4096, range: 360.0, max_speed: 100.0, invert: true},
    joint_4: {id: 4, ticks: 4096, range: 300.0, max_speed: 100.0, min_angle: -150.0, max_angle: 150.0},
    joint_5: {id: 5, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 100.0, invert: true},
    joint_6: {id: 6, ticks: 1024, range: 300.0, max_speed: 100.0, min_angle: -150.0, max_angle: 150.0},
    gripper_revolute_joint: {id: 6, ticks: 1024, range: 300.0, max_speed: 100.0, min_angle: 0.0, max_angle: 149.0, invert: true},
}
